package worker

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/manulengineer/manulheart/pkg/browser"
	"github.com/manulengineer/manulheart/pkg/config"
	"github.com/manulengineer/manulheart/pkg/dsl"
	"github.com/manulengineer/manulheart/pkg/explain"
	"github.com/manulengineer/manulheart/pkg/runtime"
	"github.com/manulengineer/manulheart/pkg/utils"
)

// Worker owns exactly one Runtime, one Page, one Browser, and (optionally)
// one ChromeProcess. A Worker is single-goroutine: every method on it must
// be called from the goroutine that constructed it.
//
// Use NewWorker to construct a Worker bound to its own Chrome instance.
// Use AdoptWorker to construct a Worker bound to an existing Page (e.g.
// for unit tests or when sharing a Chrome process across multiple tabs).
type Worker struct {
	id      int
	cfg     config.Config
	logger  *utils.Logger
	chrome  *browser.ChromeProcess
	browser browser.Browser
	page    browser.Page
	runtime *runtime.Runtime

	allocator *PortAllocator
	port      int

	closeOnce sync.Once
}

// Options configures a Worker.
type Options struct {
	// ID is a stable per-worker identifier used in logs. If 0, a synthetic
	// ID is generated by the Pool.
	ID int

	// Config is the engine-wide configuration. CDPEndpoint is overwritten
	// by the worker's own Chrome instance.
	Config config.Config

	// Logger receives worker output. If nil, a default stdout logger is created.
	// The Worker prefixes every log line with "[w<ID>] " automatically.
	Logger *utils.Logger

	// Allocator is required: the Worker calls Acquire() to bind a CDP port
	// and Release() on Close.
	Allocator *PortAllocator

	// ChromeOptions overrides launch flags. Port is always overridden by
	// Allocator.Acquire(); UserDataDir is left empty (per-worker temp dir).
	ChromeOptions browser.ChromeOptions
}

// NewWorker launches a fresh Chrome instance, dials its first page, and
// returns a ready-to-run Worker. Caller MUST call Close() to release Chrome
// and the allocated port.
func NewWorker(ctx context.Context, opts Options) (*Worker, error) {
	if opts.Allocator == nil {
		return nil, errors.New("worker: Options.Allocator is required")
	}
	port, err := opts.Allocator.Acquire()
	if err != nil {
		return nil, fmt.Errorf("worker: acquire port: %w", err)
	}

	chromeOpts := opts.ChromeOptions
	chromeOpts.Port = port
	// If the engine config requests headless, force it on every worker;
	// callers can still set ChromeOptions.Headless directly.
	if opts.Config.Headless {
		chromeOpts.Headless = true
	}

	chrome, err := browser.LaunchChrome(ctx, chromeOpts)
	if err != nil {
		opts.Allocator.Release(port)
		return nil, fmt.Errorf("worker: launch chrome: %w", err)
	}

	br := browser.NewCDPBrowser(chrome.Endpoint())
	page, err := br.FirstPage(ctx)
	if err != nil {
		_ = chrome.Close()
		opts.Allocator.Release(port)
		return nil, fmt.Errorf("worker: attach page: %w", err)
	}

	cfg := opts.Config
	cfg.CDPEndpoint = chrome.Endpoint()

	logger := opts.Logger
	if logger == nil {
		level := utils.LogLevelInfo
		if cfg.Verbose {
			level = utils.LogLevelDebug
		}
		logger = utils.NewLogger(nil).WithLevel(level)
	}
	id := opts.ID
	if id == 0 {
		id = nextSyntheticWorkerID()
	}
	logger = utils.WithPrefix(logger, fmt.Sprintf("[w%d] ", id))

	return &Worker{
		id:        id,
		cfg:       cfg,
		logger:    logger,
		chrome:    chrome,
		browser:   br,
		page:      page,
		runtime:   runtime.New(cfg, page, logger),
		allocator: opts.Allocator,
		port:      port,
	}, nil
}

// AdoptWorker wraps an existing Page in a Worker without launching Chrome
// or acquiring a port. Intended for tests, embedded use, or BYO-browser
// scenarios where lifecycle is managed externally. Close() will close the
// Page only — no Chrome teardown, no port release.
func AdoptWorker(id int, cfg config.Config, page browser.Page, logger *utils.Logger) *Worker {
	if logger == nil {
		level := utils.LogLevelInfo
		if cfg.Verbose {
			level = utils.LogLevelDebug
		}
		logger = utils.NewLogger(nil).WithLevel(level)
	}
	if id == 0 {
		id = nextSyntheticWorkerID()
	}
	logger = utils.WithPrefix(logger, fmt.Sprintf("[w%d] ", id))
	return &Worker{
		id:      id,
		cfg:     cfg,
		logger:  logger,
		page:    page,
		runtime: runtime.New(cfg, page, logger),
	}
}

// ID returns the stable worker identifier used in log prefixes.
func (w *Worker) ID() int { return w.id }

// Runtime returns the worker's bound Runtime. Returned for advanced use
// (e.g. registering hunt-scoped variables before Run); most callers should
// just use Run().
func (w *Worker) Runtime() *runtime.Runtime { return w.runtime }

// Page returns the worker's bound Page. Single-goroutine.
func (w *Worker) Page() browser.Page { return w.page }

// Run executes a parsed hunt against the worker's page.
// Block-level logging (BlockStart/BlockPass/BlockFail) is emitted per STEP
// group inside runtime.RunHunt, so this method only adds the mission header.
func (w *Worker) Run(ctx context.Context, hunt *dsl.Hunt) (*explain.HuntResult, error) {
	if w == nil || w.runtime == nil {
		return nil, errors.New("worker: zero-value Worker; use NewWorker or AdoptWorker")
	}
	w.logger.Startup("heuristics", w.cfg.CDPEndpoint)
	return w.runtime.RunHunt(ctx, hunt)
}

// Close tears down the Worker: closes the page, closes the browser
// connection, kills the Chrome process, and releases the CDP port.
// Idempotent.
func (w *Worker) Close() error {
	if w == nil {
		return nil
	}
	var firstErr error
	w.closeOnce.Do(func() {
		if w.page != nil {
			if err := w.page.Close(); err != nil && firstErr == nil {
				firstErr = err
			}
		}
		if w.browser != nil {
			if err := w.browser.Close(); err != nil && firstErr == nil {
				firstErr = err
			}
		}
		if w.chrome != nil {
			if err := w.chrome.Close(); err != nil && firstErr == nil {
				firstErr = err
			}
		}
		if w.allocator != nil && w.port != 0 {
			w.allocator.Release(w.port)
		}
	})
	return firstErr
}

// ── synthetic worker IDs ────────────────────────────────────────────────────

var (
	syntheticIDMu sync.Mutex
	syntheticID   int
)

func nextSyntheticWorkerID() int {
	syntheticIDMu.Lock()
	defer syntheticIDMu.Unlock()
	syntheticID++
	return syntheticID
}
